name: Lint & Format

on: 
  - pull_request_target

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependecies
        run: npm ci

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint
